apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-stack-kube-prom-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    route:
      receiver: "ai-webhook"
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1m

      routes:
        - match:
            alertname: AIAlertsIncreasing
          receiver: "ai-webhook"

    receivers:
      - name: "ai-webhook"
        webhook_configs:
          - url: "http://ai-engine.ai-self-healing.svc.cluster.local:8000/alert"
            send_resolved: true