apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-engine-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: ai-engine
  namespaceSelector:
    matchNames:
    - ai-self-healing
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    
    
    
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: execution-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: execution
  namespaceSelector:
    matchNames:
    - ai-self-healing
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: notification
  namespaceSelector:
    matchNames:
    - ai-self-healing
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-monitoring-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: monitoring
  namespaceSelector:
    matchNames:
    - ai-self-healing
  endpoints:
  - port: http
    path: /metrics
    interval: 15s