apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alerts
  namespace: monitoring
  labels:
    release: prometheus-stack
    role: alert-rules
spec:
  groups:
  - name: test-alerts
    rules:
    - alert: AIAlertsIncreasing
      expr: rate(ai_alerts_total[1m]) > 0
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "AI Engine receiving alerts"